// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Melene.Migrations
{
    [DbContext(typeof(MeleneDbContext))]
    [Migration("20250928044315_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreMeasures", b =>
                {
                    b.Property<string>("coreID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<string>("CpuName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<float>("c0Residency")
                        .HasColumnType("real");

                    b.Property<float>("frequency")
                        .HasColumnType("real");

                    b.Property<float>("frequencyEff")
                        .HasColumnType("real");

                    b.Property<float>("load")
                        .HasColumnType("real");

                    b.Property<float>("temperature")
                        .HasColumnType("real");

                    b.HasKey("coreID", "timestamp");

                    b.HasIndex("CpuName");

                    b.ToTable("core_measures", (string)null);
                });

            modelBuilder.Entity("CoreThread", b =>
                {
                    b.Property<int>("threadID")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(1);

                    b.Property<string>("CoreMeasuresId")
                        .HasColumnType("text");

                    b.Property<float>("load")
                        .HasColumnType("real");

                    b.HasKey("threadID", "timeStamp");

                    b.ToTable("core_threads", (string)null);
                });

            modelBuilder.Entity("Cpu", b =>
                {
                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("coreCount")
                        .HasColumnType("integer");

                    b.Property<float>("frequencyLimit")
                        .HasColumnType("real");

                    b.Property<string>("l1Instruction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("l1Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("l2Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("l3Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("socket")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("name");

                    b.ToTable("cpus", (string)null);
                });

            modelBuilder.Entity("CpuMeasures", b =>
                {
                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CpuName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<float>("VDDCRPower")
                        .HasColumnType("real");

                    b.Property<float>("VDDCRSOCPower")
                        .HasColumnType("real");

                    b.Property<string>("cHTCLimit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("coreSpeedAverage")
                        .HasColumnType("real");

                    b.Property<string>("currentMode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("edcCurrentLimit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("edcCurrentValue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("maxLoadOfOneCore")
                        .HasColumnType("real");

                    b.Property<float>("peakCoreSpeed")
                        .HasColumnType("real");

                    b.Property<float>("peakCoreVoltage")
                        .HasColumnType("real");

                    b.Property<float>("pptCurrentLimit")
                        .HasColumnType("real");

                    b.Property<float>("pptCurrentValue")
                        .HasColumnType("real");

                    b.Property<string>("tdcCurrentLimit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("tdcCurrentValue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("temperature")
                        .HasColumnType("real");

                    b.Property<float>("totalLoad")
                        .HasColumnType("real");

                    b.HasKey("timestamp");

                    b.HasIndex("CpuName");

                    b.ToTable("cpu_measures", (string)null);
                });

            modelBuilder.Entity("GPUMeasure", b =>
                {
                    b.Property<DateTime>("timeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("freeMemory")
                        .HasColumnType("real");

                    b.Property<float>("gpuCoreTemperature")
                        .HasColumnType("real");

                    b.Property<string>("gpuName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<float>("memoryTemperature")
                        .HasColumnType("real");

                    b.Property<float>("memoryUsage")
                        .HasColumnType("real");

                    b.Property<float>("temperatureHotspot")
                        .HasColumnType("real");

                    b.Property<float>("totalMemory")
                        .HasColumnType("real");

                    b.Property<float>("totalMemoryUsage")
                        .HasColumnType("real");

                    b.HasKey("timeStamp");

                    b.ToTable("gpu_measures", (string)null);
                });

            modelBuilder.Entity("MemoryMeasure", b =>
                {
                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("available")
                        .HasColumnType("real");

                    b.Property<float>("loadInPercentage")
                        .HasColumnType("real");

                    b.Property<string>("memoryID")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("total")
                        .HasColumnType("real");

                    b.Property<float>("used")
                        .HasColumnType("real");

                    b.HasKey("timestamp");

                    b.ToTable("memory_measures", (string)null);
                });

            modelBuilder.Entity("CoreMeasures", b =>
                {
                    b.HasOne("Cpu", "Cpu")
                        .WithMany()
                        .HasForeignKey("CpuName");

                    b.Navigation("Cpu");
                });

            modelBuilder.Entity("CpuMeasures", b =>
                {
                    b.HasOne("Cpu", "cpu")
                        .WithMany()
                        .HasForeignKey("CpuName");

                    b.Navigation("cpu");
                });
#pragma warning restore 612, 618
        }
    }
}
