// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Melene.Migrations
{
    [DbContext(typeof(MeleneDbContext))]
    [Migration("20260131203814_gpuCoreClock")]
    partial class gpuCoreClock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Melene.Db.CoreMeasuresEntity", b =>
                {
                    b.Property<int>("CoreID")
                        .HasColumnType("integer")
                        .HasColumnName("core_id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasColumnOrder(1);

                    b.Property<float>("C0Residency")
                        .HasColumnType("real")
                        .HasColumnName("c0_residency");

                    b.Property<string>("CpuName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpu_name");

                    b.Property<float>("Frequency")
                        .HasColumnType("real")
                        .HasColumnName("frequency");

                    b.Property<float>("FrequencyEff")
                        .HasColumnType("real")
                        .HasColumnName("frequency_eff");

                    b.Property<float>("Load")
                        .HasColumnType("real")
                        .HasColumnName("load");

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature");

                    b.HasKey("CoreID", "Timestamp");

                    b.HasIndex("CpuName");

                    b.ToTable("core_measures");
                });

            modelBuilder.Entity("Melene.Db.CoreThreadEntity", b =>
                {
                    b.Property<int>("ThreadID")
                        .HasColumnType("integer")
                        .HasColumnName("thread_id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_stamp")
                        .HasColumnOrder(1);

                    b.Property<int>("CoreID")
                        .HasColumnType("integer")
                        .HasColumnName("core_id");

                    b.Property<DateTime>("CoreTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("core_timestamp");

                    b.Property<float>("Load")
                        .HasColumnType("real")
                        .HasColumnName("load");

                    b.HasKey("ThreadID", "TimeStamp");

                    b.HasIndex("CoreID", "CoreTimestamp");

                    b.ToTable("core_threads");
                });

            modelBuilder.Entity("Melene.Db.CpuEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("CoreCount")
                        .HasColumnType("integer")
                        .HasColumnName("core_count");

                    b.Property<float>("FrequencyLimit")
                        .HasColumnType("real")
                        .HasColumnName("frequency_limit");

                    b.Property<string>("L1Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("l1_instruction");

                    b.Property<string>("L1Size")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("l1_size");

                    b.Property<string>("L2Size")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("l2_size");

                    b.Property<string>("L3Size")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("l3_size");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("socket");

                    b.HasKey("Name");

                    b.ToTable("cpus");
                });

            modelBuilder.Entity("Melene.Db.CpuMeasuresEntity", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("CHTCLimit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("chtc_limit");

                    b.Property<float>("CoreSpeedAverage")
                        .HasColumnType("real")
                        .HasColumnName("core_speed_average");

                    b.Property<string>("CpuName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpu_name");

                    b.Property<string>("CurrentMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_mode");

                    b.Property<string>("EdcCurrentLimit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("edc_current_limit");

                    b.Property<string>("EdcCurrentValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("edc_current_value");

                    b.Property<float>("MaxLoadOfOneCore")
                        .HasColumnType("real")
                        .HasColumnName("max_load_of_one_core");

                    b.Property<float>("PeakCoreSpeed")
                        .HasColumnType("real")
                        .HasColumnName("peak_core_speed");

                    b.Property<float>("PeakCoreVoltage")
                        .HasColumnType("real")
                        .HasColumnName("peak_core_voltage");

                    b.Property<float>("PptCurrentLimit")
                        .HasColumnType("real")
                        .HasColumnName("ppt_current_limit");

                    b.Property<float>("PptCurrentValue")
                        .HasColumnType("real")
                        .HasColumnName("ppt_current_value");

                    b.Property<string>("TdcCurrentLimit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tdc_current_limit");

                    b.Property<string>("TdcCurrentValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tdc_current_value");

                    b.Property<float>("Temperature")
                        .HasColumnType("real")
                        .HasColumnName("temperature");

                    b.Property<float>("TotalLoad")
                        .HasColumnType("real")
                        .HasColumnName("total_load");

                    b.Property<float>("VDDCRPower")
                        .HasColumnType("real")
                        .HasColumnName("vddcr_power");

                    b.Property<float>("VDDCRSOCPower")
                        .HasColumnType("real")
                        .HasColumnName("vddcr_soc_power");

                    b.HasKey("Timestamp");

                    b.HasIndex("CpuName");

                    b.ToTable("cpu_measures");
                });

            modelBuilder.Entity("Melene.Db.GpuMeasureEntity", b =>
                {
                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_stamp");

                    b.Property<float>("FreeMemory")
                        .HasColumnType("real")
                        .HasColumnName("free_memory");

                    b.Property<float>("GpuCoreClock")
                        .HasColumnType("real")
                        .HasColumnName("gpu_core_clock");

                    b.Property<float>("GpuCoreTemperature")
                        .HasColumnType("real")
                        .HasColumnName("gpu_core_temperature");

                    b.Property<string>("GpuName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gpu_name");

                    b.Property<float>("MemoryTemperature")
                        .HasColumnType("real")
                        .HasColumnName("memory_temperature");

                    b.Property<float>("MemoryUsage")
                        .HasColumnType("real")
                        .HasColumnName("memory_usage");

                    b.Property<float>("TemperatureHotspot")
                        .HasColumnType("real")
                        .HasColumnName("temperature_hotspot");

                    b.Property<float>("TotalMemory")
                        .HasColumnType("real")
                        .HasColumnName("total_memory");

                    b.Property<float>("TotalMemoryUsage")
                        .HasColumnType("real")
                        .HasColumnName("total_memory_usage");

                    b.HasKey("TimeStamp");

                    b.ToTable("gpu_measures");
                });

            modelBuilder.Entity("Melene.Db.MemoryMeasureEntity", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<float>("Available")
                        .HasColumnType("real")
                        .HasColumnName("available");

                    b.Property<float>("LoadInPercentage")
                        .HasColumnType("real")
                        .HasColumnName("load_in_percentage");

                    b.Property<string>("MemoryID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("memory_id");

                    b.Property<float>("Total")
                        .HasColumnType("real")
                        .HasColumnName("total");

                    b.Property<float>("Used")
                        .HasColumnType("real")
                        .HasColumnName("used");

                    b.HasKey("Timestamp");

                    b.ToTable("memory_measures");
                });

            modelBuilder.Entity("Melene.Db.CoreMeasuresEntity", b =>
                {
                    b.HasOne("Melene.Db.CpuEntity", "Cpu")
                        .WithMany("CoreMeasures")
                        .HasForeignKey("CpuName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpu");
                });

            modelBuilder.Entity("Melene.Db.CoreThreadEntity", b =>
                {
                    b.HasOne("Melene.Db.CoreMeasuresEntity", "CoreMeasures")
                        .WithMany("CoreThreads")
                        .HasForeignKey("CoreID", "CoreTimestamp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoreMeasures");
                });

            modelBuilder.Entity("Melene.Db.CpuMeasuresEntity", b =>
                {
                    b.HasOne("Melene.Db.CpuEntity", "Cpu")
                        .WithMany("CpuMeasures")
                        .HasForeignKey("CpuName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cpu");
                });

            modelBuilder.Entity("Melene.Db.CoreMeasuresEntity", b =>
                {
                    b.Navigation("CoreThreads");
                });

            modelBuilder.Entity("Melene.Db.CpuEntity", b =>
                {
                    b.Navigation("CoreMeasures");

                    b.Navigation("CpuMeasures");
                });
#pragma warning restore 612, 618
        }
    }
}
